apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::946278464249:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1INL5JAB3TWMV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::946278464249:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T05:09:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1609"
  uid: 9b59f64f-ab4d-4807-9201-ec6b175f303b
